module.exports = Object.freeze({
  IDLE: 'IDLE',
  CHECKING: 'CHECKING',
  UPDATE_AVAILABLE: 'UPDATE_AVAILABLE',
  DOWNLOADING: 'DOWNLOADING',
  PAUSED: 'PAUSED',
  VERIFYING: 'VERIFYING',
  READY: 'READY',
  INSTALLING: 'INSTALLING',
  COMPLETED: 'COMPLETED',
  FAILED: 'FAILED',
  OFFLINE: 'OFFLINE'
});
