'use strict';

const { EntityManager, createDefaultEntityManager } = require('./EntityManager');
const ENTITY_UNDERSTANDING_VERSION = '6.0.0';

module.exports = {
  ENTITY_UNDERSTANDING_VERSION,
  EntityPipeline: require('./EntityPipeline'),
  EntityManager,
  createDefaultEntityManager,
  EntityContext: require('./EntityContext'),
  EntityRegistry: require('./EntityRegistry'),
  EntityExtractor: require('./EntityExtractor'),
  BaseEntityExtractor: require('./BaseEntityExtractor'),
  EntityNormalizer: require('./EntityNormalizer'),
  EntityResolver: require('./EntityResolver'),
  EntityValidator: require('./EntityValidator'),
  EntityRelationshipBuilder: require('./EntityRelationshipBuilder'),
  EntityGraphBuilder: require('./EntityGraphBuilder'),
  StructuredEntities: require('./StructuredEntities'),
  ApplicationExtractor: require('./ApplicationExtractor'),
  BrowserExtractor: require('./BrowserExtractor'),
  WebsiteExtractor: require('./WebsiteExtractor'),
  FileExtractor: require('./FileExtractor'),
  FolderExtractor: require('./FolderExtractor'),
  PathExtractor: require('./PathExtractor'),
  MediaExtractor: require('./MediaExtractor'),
  ContactExtractor: require('./ContactExtractor'),
  PersonExtractor: require('./PersonExtractor'),
  DeviceExtractor: require('./DeviceExtractor'),
  LocationExtractor: require('./LocationExtractor'),
  DateExtractor: require('./DateExtractor'),
  TimeExtractor: require('./TimeExtractor'),
  DurationExtractor: require('./DurationExtractor'),
  ReminderExtractor: require('./ReminderExtractor'),
  AlarmExtractor: require('./AlarmExtractor'),
  TimerExtractor: require('./TimerExtractor'),
  WindowExtractor: require('./WindowExtractor'),
  NetworkExtractor: require('./NetworkExtractor'),
  VolumeExtractor: require('./VolumeExtractor'),
  BrightnessExtractor: require('./BrightnessExtractor'),
  EntityConfiguration: require('./EntityConfiguration'),
  EntityDiagnostics: require('./EntityDiagnostics'),
  EntityLogger: require('./EntityLogger'),
  EntityUnderstandingStage: require('./EntityUnderstandingStage'),
  ...require('./EntityErrors')
};
