const INSTALLATION_STATES = Object.freeze({
  UNINITIALIZED: 'UNINITIALIZED',
  IDLE: 'IDLE',
  READY: 'READY',
  WAITING_CONFIRMATION: 'WAITING_CONFIRMATION',
  CONFIRMED: 'CONFIRMED',
  PREPARING: 'PREPARING',
  SHUTTING_DOWN: 'SHUTTING_DOWN',
  LAUNCHING_INSTALLER: 'LAUNCHING_INSTALLER',
  INSTALLER_RUNNING: 'INSTALLER_RUNNING',
  COMPLETED: 'COMPLETED',
  CANCELLED: 'CANCELLED',
  FAILED: 'FAILED',
  ERROR: 'ERROR'
});

module.exports = INSTALLATION_STATES;
