const VERSION_CHECK_STATES = Object.freeze({
  UNKNOWN: 'UNKNOWN',
  CHECKING: 'CHECKING',
  UP_TO_DATE: 'UP_TO_DATE',
  UPDATE_AVAILABLE: 'UPDATE_AVAILABLE',
  ERROR: 'ERROR',
  OFFLINE: 'OFFLINE',
  INVALID_RESPONSE: 'INVALID_RESPONSE'
});

module.exports = {
  VERSION_CHECK_STATES
};
