const DOWNLOAD_STATES = Object.freeze({
  IDLE: 'IDLE',
  QUEUED: 'QUEUED',
  CONNECTING: 'CONNECTING',
  DOWNLOADING: 'DOWNLOADING',
  PAUSED: 'PAUSED',
  RESUMING: 'RESUMING',
  RETRYING: 'RETRYING',
  COMPLETED: 'COMPLETED',
  FAILED: 'FAILED',
  CANCELLED: 'CANCELLED',
  ERROR: 'ERROR'
});

module.exports = DOWNLOAD_STATES;
