const assert = require('assert');
const fs = require('fs');
const path = require('path');

describe('Planner Renderer', function() {
  const rendererRoot = path.join(__dirname, '..', '..', 'apps', 'desktop', 'renderer', 'planner');
  const html = fs.readFileSync(path.join(rendererRoot, 'index.html'), 'utf8');
  const css = fs.readFileSync(path.join(rendererRoot, 'index.css'), 'utf8');
  const script = fs.readFileSync(path.join(rendererRoot, 'index.js'), 'utf8');
  const mainScript = fs.readFileSync(path.join(__dirname, '..', '..', 'apps', 'desktop', 'electron', 'main.js'), 'utf8');

  it('should render calendar and timetable in an assistant-matched glass window', function() {
    assert.match(html, /class="planner-shell"/);
    assert.doesNotMatch(html, /id="calendar-tab"/);
    assert.doesNotMatch(html, /id="timetable-tab"/);
    assert.doesNotMatch(html, /id="timetable-date"/);
    assert.doesNotMatch(html, /id="today-button"/);
    assert.match(html, /id="month-picker-button"/);
    assert.match(html, /id="year-picker-button"/);
    assert.match(html, /id="month-picker-popover"[^>]*hidden/);
    assert.match(html, /id="year-picker-popover"[^>]*hidden/);
    assert.match(html, /id="month-picker-list"/);
    assert.match(html, /id="year-picker-list"/);
    assert.doesNotMatch(html, /id="date-picker-popover"/);
    assert.doesNotMatch(html, /id="month-slider"/);
    assert.doesNotMatch(html, /id="year-slider"/);
    assert.doesNotMatch(html, /type="range"/);
    assert.match(html, /id="month-grid"/);
    assert.match(html, /id="time-grid"/);
    assert.match(html, /id="quick-add-toggle"/);
    assert.match(html, /id="quick-add-close"/);
    assert.match(html, /id="side-panel"[^>]*hidden/);
    assert.match(html, /id="quick-add"/);
    assert.match(html, /id="quick-add-submit"/);
    assert.match(css, /--panel-bg:\s*rgba\(20,\s*20,\s*40,\s*0\.92\)/);
    assert.match(css, /backdrop-filter:\s*blur\(18px\)\s*saturate\(115%\)/);
    assert.match(css, /var\(--glass-shadow\)/);
    assert.doesNotMatch(html, /class="view-switch"/);
    assert.match(css, /\.content-grid\s*\{[\s\S]*grid-template-columns:\s*minmax\(0,\s*1\.25fr\)\s*minmax\(320px,\s*0\.75fr\)/);
    assert.match(css, /\.planner-shell\.date-selected \.content-grid/);
    assert.match(css, /grid-template-columns:\s*minmax\(0,\s*1\.25fr\)\s*minmax\(320px,\s*0\.75fr\)/);
    assert.match(css, /\.timetable-view\s*\{[\s\S]*display:\s*flex;[\s\S]*opacity:\s*1;/);
    assert.match(css, /\.planner-shell\.date-selected \.timetable-view/);
    assert.match(css, /@keyframes timetable-reveal/);
    assert.match(css, /\.day-cell\.selected/);
    assert.match(css, /\.month-title-button/);
    assert.match(css, /\.date-picker-popover/);
    assert.match(css, /\.month-picker-popover/);
    assert.match(css, /\.year-picker-popover/);
    assert.match(css, /\.picker-scroll-list/);
    assert.match(css, /\.picker-option\.selected/);
    assert.doesNotMatch(css, /\.picker-field input\[type="range"\]/);
    assert.match(css, /\.day-cell:active/);
    assert.match(css, /\.day-reminder-count/);
    assert.match(css, /\.day-item\.schedule-reminder/);
    assert.match(css, /\.slot-entry\.schedule-alarm/);
    assert.match(css, /\.time-grid::-webkit-scrollbar/);
    assert.match(css, /scrollbar-width:\s*none/);
    assert.match(css, /\.side-panel\[hidden\]/);
    assert.match(css, /\.side-panel-head/);
    assert.match(css, /\.panel-close-button/);
    assert.match(css, /\.primary-button:disabled/);
    assert.match(css, /--quick-add-shell/);
    assert.match(css, /--quick-add-control/);
    assert.match(css, /backdrop-filter:\s*blur\(14px\)\s*saturate\(118%\)/);
    assert.match(css, /contain:\s*layout paint/);
    assert.match(css, /--adaptive-text-shadow/);
    assert.match(css, /prefers-reduced-motion:\s*reduce/);
    assert.match(css, /html\[data-glass-contrast\]/);
    assert.match(script, /getSettings/);
    assert.match(script, /onSettingsChanged/);
    assert.match(script, /const shellAlpha = useDarkText \? 0\.78 \+ \(strength \* 0\.14\) : 0\.72 \+ \(strength \* 0\.2\)/);
    assert.match(script, /formatAlpha\(shellAlpha\)/);
    assert.match(script, /--quick-add-shell/);
    assert.match(script, /setQuickAddOpen/);
    assert.match(script, /quickAddCloseEl\.addEventListener\('click'/);
    assert.match(script, /quickAddSubmitEl\.disabled = true/);
    assert.doesNotMatch(script, /todayButtonEl/);
    assert.match(script, /function setPickerOpen\(kind\)/);
    assert.match(script, /function renderMonthPicker\(\)/);
    assert.match(script, /function renderYearPicker\(\)/);
    assert.match(script, /function setVisibleMonthPart\(month, year\)/);
    assert.match(script, /monthPickerListEl/);
    assert.match(script, /yearPickerListEl/);
    assert.doesNotMatch(script, /monthSliderEl/);
    assert.doesNotMatch(script, /yearSliderEl/);
    assert.match(script, /selectedDateKey/);
    assert.match(script, /scheduleRender/);
    assert.match(script, /requestAnimationFrame/);
    assert.match(script, /day-reminder-count/);
    assert.match(script, /function isScheduleEntry\(entry\)/);
    assert.match(script, /const calendarEntries = allDayEntries\.filter\(entry => !isScheduleEntry\(entry\)\)/);
    assert.match(script, /sourceKind/);
    assert.match(script, /date-selected/);
    assert.match(script, /getPlannerEntries/);
    assert.match(script, /addPlannerEntry/);
    assert.match(script, /deletePlannerEntry/);
    assert.match(script, /onPlannerView/);
    assert.match(script, /onPlannerEntriesChanged/);
    assert.match(script, /closePlanner/);
    assert.match(mainScript, /function createPlannerWindow/);
    assert.match(mainScript, /function scheduleToPlannerEntry/);
    assert.match(mainScript, /function getPlannerEntriesForRenderer/);
    assert.match(mainScript, /planner:entriesChanged/);
    assert.match(mainScript, /transparent:\s*true/);
    assert.match(mainScript, /show:\s*false/);
    assert.match(mainScript, /paintWhenInitiallyHidden:\s*true/);
    assert.match(mainScript, /ready-to-show/);
    assert.match(mainScript, /function lowerChatWindowForPlanner/);
    assert.match(mainScript, /chatWindow\.setAlwaysOnTop\(false\)/);
    assert.match(mainScript, /lowerChat:\s*true/);
    assert.match(mainScript, /backgroundColor:\s*'#00000000'/);
  });
});
