const assert = require('assert');
const fs = require('fs');
const path = require('path');

describe('Dynamic Island Schedule Alerts', function() {
  const root = path.join(__dirname, '..', '..');
  const preload = fs.readFileSync(path.join(root, 'apps', 'desktop', 'preload.js'), 'utf8');
  const main = fs.readFileSync(path.join(root, 'apps', 'desktop', 'electron', 'main.js'), 'utf8');
  const voiceWindow = fs.readFileSync(path.join(root, 'apps', 'desktop', 'voice', 'ui', 'VoiceWindowController.js'), 'utf8');
  const voiceOverlay = fs.readFileSync(path.join(root, 'apps', 'desktop', 'voice', 'ui', 'VoiceOverlay.js'), 'utf8');

  it('should render schedule alerts inside the Dynamic Island with inline actions', function() {
    assert.equal(fs.existsSync(path.join(root, 'apps', 'desktop', 'renderer', 'alert')), false);
    assert.match(main, /function presentScheduleInDynamicIsland\(schedule = \{\}\)/);
    assert.match(main, /function buildScheduleDynamicIslandActions\(schedule = \{\}\)/);
    assert.match(main, /function formatScheduleRecurrenceLabel\(recurrence = ''\)/);
    assert.match(main, /function scheduleActionId\(schedule = \{\}\)/);
    assert.match(main, /intent: 'schedule\.due'/);
    assert.match(main, /label: 'Snooze 5 min'/);
    assert.match(main, /label: 'Stop'/);
    assert.match(main, /actions: buildScheduleDynamicIslandActions\(schedule\)/);
    assert.match(main, /resultEntries: \[\]/);
    assert.match(main, /recurrenceLabel/);
    assert.match(main, /scheduleId,\s*\n\s*primary: true/s);
    assert.match(main, /persistUntilAction: true/);
    assert.match(main, /autoHideMs: 0/);
    assert.match(main, /function isTrustedVoiceOverlayIpcSender\(event, channel\)/);
    assert.doesNotMatch(main, /function cleanCommunicationContactTitle/);
    assert.doesNotMatch(main, /function presentCommunicationContactChoicesInDynamicIsland/);
    assert.doesNotMatch(main, /'communication:selectContact'/);
    assert.doesNotMatch(main, /'communication:sendPrepared'/);
    assert.doesNotMatch(main, /'communication:cancelPrepared'/);
    assert.doesNotMatch(main, /data:\s*\{\s*choices,\s*actions: choices\.slice/s);
    assert.match(main, /event\?\.sender\?\.id !== overlayContents\.id/);
    assert.match(main, /trustedVoiceOverlaySender: isTrustedVoiceOverlayIpcSender\(event, channel\)/);
    assert.doesNotMatch(main, /new BrowserWindow\(\{\s*width:\s*420,\s*height:\s*440/s);
    assert.doesNotMatch(main, /windowType: 'schedule-alert'/);
    assert.doesNotMatch(main, /alertWindow/);

    assert.match(voiceOverlay, /actions: this\._normalizeActions\(result\)/);
    assert.match(voiceOverlay, /schedule: this\._normalizeSchedule\(result, intent\)/);
    assert.match(voiceOverlay, /_normalizeSchedule\(result = \{\}, intent = ''\)/);
    assert.match(voiceOverlay, /intent === 'schedule\.due' \|\| intent === 'schedule\.live'/);
    assert.match(voiceOverlay, /if \(intent === 'schedule\.due' \|\| intent === 'schedule\.live'\) \{\s*\n\s*return \[\];\s*\n\s*\}/s);
    assert.match(voiceOverlay, /draftId: String\(action\?\.draftId \|\| ''\)/);
    assert.match(voiceOverlay, /provider: String\(action\?\.provider \|\| ''\)/);
    assert.match(voiceOverlay, /choiceIndex: Math\.max\(0, Math\.min\(8, Number\(action\?\.choiceIndex\) \|\| 0\)\)/);
    assert.match(voiceOverlay, /\['snooze', 'stop'\]\.includes\(action\.kind \|\| action\.id\)/);
    assert.match(preload, /function appendVoiceActions\(fragment, payload = \{\}\)/);
    assert.match(preload, /function appendVoiceScheduleDue\(fragment, payload = \{\}\)/);
    assert.match(preload, /function appendVoiceScheduleLive\(fragment, payload = \{\}\)/);
    assert.match(preload, /function updateVoiceLiveScheduleDom\(panel, schedule = \{\}\)/);
    assert.match(preload, /function formatVoiceIcon\(value, fallback = 'JA'\)/);
    assert.match(preload, /voice-schedule-due/);
    assert.match(preload, /voice-schedule-live/);
    assert.match(preload, /voiceOverlay:expandLiveSchedule/);
    assert.match(preload, /schedule-due-result/);
    assert.match(preload, /schedule-live-compact/);
    assert.match(preload, /if \(isScheduleDue\) \{\s*\n\s*appendVoiceScheduleDue\(fragment, payload\);\s*\n\s*\}/s);
    assert.doesNotMatch(preload, /ipcRenderer\.invoke\('communication:/);
    assert.match(preload, /ipcRenderer\.invoke\('schedule:alertAction'/);
    assert.match(preload, /ipcRenderer\.invoke\('voiceOverlay:collapse', options\)/);
    assert.match(preload, /hideAfterMs: 5000/);
    assert.match(preload, /function buildVoiceActionFeedback\(action = \{\}, result = \{\}\)/);
    assert.match(preload, /setVoiceActionRowResolving\(row, button, true\)/);
    assert.match(preload, /Snoozing\.\.\./);
    assert.match(preload, /Stopping\.\.\./);
    assert.match(preload, /const scheduleAction = kind === 'end' \? 'stop' : kind/);
    assert.match(preload, /button\.setAttribute\('aria-label', button\.textContent\)/);
    assert.match(preload, /keepExpandedResult/);
    assert.match(preload, /function playVoiceScheduleSound\(kind\)/);
    assert.match(preload, /function stopVoiceAlertSound\(\)/);
    assert.match(preload, /function makeVoiceWebCardOpenable\(item, url\)/);
    assert.match(preload, /item\.classList\.add\('voice-card-openable'\)/);
    assert.match(preload, /item\.setAttribute\('role', 'button'\)/);
    assert.match(preload, /ipcRenderer\.invoke\('browser:openExternal', \{ url \}\)/);
    assert.doesNotMatch(preload, /voice-card-link/);
    assert.match(preload, /function scheduleVoiceHoverAutoHide\(payload = \{\}\)/);
    assert.match(preload, /function refreshVoiceHoverPointerState\(root = document\.getElementById\('voice-overlay'\)\)/);
    assert.match(preload, /function watchVoiceHoverExit\(root = document\.getElementById\('voice-overlay'\)\)/);
    assert.match(preload, /payload\.hoverHoldAutoHide !== true/);
    assert.match(preload, /root\.matches\?\.\(':hover'\)/);
    assert.match(preload, /document\.elementFromPoint\(voiceHoverPointerPosition\.x, voiceHoverPointerPosition\.y\)/);
    assert.match(preload, /collapseVoiceHoverAutoHideResult\(5000\)/);
    assert.match(voiceWindow, /\.voice-action-row/);
    assert.match(voiceWindow, /position: sticky; bottom: 0/);
    assert.match(voiceWindow, /\.voice-action-row\.is-resolving/);
    assert.match(voiceWindow, /\.voice-action\[disabled\]\[data-active\]/);
    assert.match(voiceWindow, /collapseAssistantResult\(options = \{\}\)/);
    assert.match(voiceWindow, /this\.hide\(\)/);
    assert.match(voiceWindow, /\.voice-card-body/);
    assert.match(voiceWindow, /\.voice-schedule-due/);
    assert.match(voiceWindow, /\.voice-schedule-title/);
    assert.match(voiceWindow, /\.voice-schedule-live/);
    assert.match(voiceWindow, /\.voice-live-ring/);
    assert.match(voiceWindow, /#voice-overlay\.schedule-live-compact/);
    assert.match(voiceWindow, /#voice-overlay\.schedule-due-result #assistant-response/);
    assert.match(voiceWindow, /#voice-overlay\.schedule-due-result \.voice-action-row/);
    assert.match(voiceWindow, /#voice-overlay\.expanded\.large #assistant-response/);
    assert.match(voiceWindow, /#voice-overlay\.expanded\.large \.voice-card-list/);
    assert.match(voiceWindow, /#voice-overlay\.expanded\.large \.voice-response-text/);
    assert.match(voiceWindow, /\.voice-card-openable/);
    assert.doesNotMatch(voiceWindow, /\.voice-card-link/);
    assert.match(voiceWindow, /dismissAssistantResultForIntent\(intent, options = \{\}\)/);
    assert.match(voiceWindow, /hasStickyAssistantResult\(intent = ''\)/);
    assert.match(voiceOverlay, /hasStickyAssistantResult\?\.\(\)/);
    assert.match(main, /dismissAssistantResultForIntent\?\.\('browser\.search'/);
    assert.doesNotMatch(main, /return \{ success: true, dismissedResult: true, intent: 'browser\.search' \}/);
    assert.match(voiceWindow, /payload\.intent === 'schedule\.due' \|\| payload\.intent === 'schedule\.live'/);
    assert.match(voiceWindow, /payload\.hoverHoldAutoHide !== true/);
    assert.match(voiceOverlay, /persistentBrowserSearch = intent === 'browser\.search'/);
    assert.match(voiceOverlay, /hoverHoldAutoHide = intent === 'phone\.notification'/);
    assert.match(voiceOverlay, /autoHideMs: hoverHoldAutoHide \? 15000 : persistentBrowserSearch \? 0/);
    assert.match(voiceOverlay, /persistUntilAction: persistentBrowserSearch \? true/);
    assert.match(main, /intent: 'phone\.notification'/);
    assert.match(main, /autoHideMs: 15000/);
    assert.match(main, /browser:openExternal/);
    assert.match(voiceWindow, /-webkit-line-clamp: 2/);
    assert.match(voiceWindow, /resultSticky/);
    assert.match(voiceWindow, /scrollbar-width: none/);
    assert.match(preload, /voice-content-summary/);
    assert.match(preload, /voice-card-path/);
  });
});
