'use strict';

const {
  EntityManager,
  createDefaultEntityManager,
  EntityUnderstandingStage
} = require('./EntityManager');
const {
  EntityConfiguration,
  EntityContext,
  EntityDiagnostics,
  EntityError,
  EntityExtractionError,
  EntityResolutionError,
  EntityValidationError,
  EntityGraphError,
  ConfigurationError,
  ExtractorExecutionError,
  EntityGraphBuilder,
  EntityLogger,
  EntityNormalizer,
  EntityPipeline,
  EntityRegistry,
  EntityRelationshipBuilder,
  EntityResolver,
  EntityValidator,
  StructuredEntities,
  BaseEntityExtractor,
  SELF_CANONICAL,
  SELF_ALIASES,
  RELATIONSHIP_ALIASES,
  allRelationshipTerms,
  findRelationshipMentions,
  findSelfReferences,
  isRelationshipTerm,
  isSelfReference,
  matchesSelfValue,
  normalizePersonReference,
  normalizeRelationship,
  normalizeToken,
  personValuesMatch,
  relationshipAliasesFor,
  relationshipValuesMatch,
  textMentionsPerson,
  textMentionsRelationship
} = require('./EntityCore');
const {
  ApplicationExtractor,
  BrowserExtractor,
  WebsiteExtractor,
  FileExtractor,
  FolderExtractor,
  PathExtractor,
  MediaExtractor,
  ContactExtractor,
  PersonExtractor,
  DeviceExtractor,
  LocationExtractor,
  DateExtractor,
  TimeExtractor,
  DurationExtractor,
  ReminderExtractor,
  AlarmExtractor,
  TimerExtractor,
  WindowExtractor,
  NetworkExtractor,
  VolumeExtractor,
  BrightnessExtractor
} = require('./EntityExtractors');
const EntityExtractor = require('./EntityExtractor');

const ENTITY_UNDERSTANDING_VERSION = '6.0.0';

module.exports = {
  ENTITY_UNDERSTANDING_VERSION,
  EntityPipeline,
  EntityManager,
  createDefaultEntityManager,
  EntityContext,
  EntityRegistry,
  EntityExtractor,
  BaseEntityExtractor,
  EntityNormalizer,
  EntityResolver,
  EntityValidator,
  EntityRelationshipBuilder,
  EntityGraphBuilder,
  StructuredEntities,
  ApplicationExtractor,
  BrowserExtractor,
  WebsiteExtractor,
  FileExtractor,
  FolderExtractor,
  PathExtractor,
  MediaExtractor,
  ContactExtractor,
  PersonExtractor,
  PersonLexicon: {
    SELF_CANONICAL,
    SELF_ALIASES,
    RELATIONSHIP_ALIASES,
    allRelationshipTerms,
    findRelationshipMentions,
    findSelfReferences,
    isRelationshipTerm,
    isSelfReference,
    matchesSelfValue,
    normalizePersonReference,
    normalizeRelationship,
    normalizeToken,
    personValuesMatch,
    relationshipAliasesFor,
    relationshipValuesMatch,
    textMentionsPerson,
    textMentionsRelationship
  },
  DeviceExtractor,
  LocationExtractor,
  DateExtractor,
  TimeExtractor,
  DurationExtractor,
  ReminderExtractor,
  AlarmExtractor,
  TimerExtractor,
  WindowExtractor,
  NetworkExtractor,
  VolumeExtractor,
  BrightnessExtractor,
  EntityConfiguration,
  EntityDiagnostics,
  EntityLogger,
  EntityUnderstandingStage,
  EntityError,
  EntityExtractionError,
  EntityResolutionError,
  EntityValidationError,
  EntityGraphError,
  ConfigurationError,
  ExtractorExecutionError
};