const RECOVERY_STATES = Object.freeze({
  IDLE: 'IDLE',
  BACKUP_CREATED: 'BACKUP_CREATED',
  INSTALLING: 'INSTALLING',
  STARTUP_VALIDATION: 'STARTUP_VALIDATION',
  RECOVERY_REQUIRED: 'RECOVERY_REQUIRED',
  ROLLBACK_PREPARING: 'ROLLBACK_PREPARING',
  ROLLBACK_RUNNING: 'ROLLBACK_RUNNING',
  RESTORING_STATE: 'RESTORING_STATE',
  RESTARTING: 'RESTARTING',
  RECOVERY_COMPLETED: 'RECOVERY_COMPLETED',
  RECOVERY_FAILED: 'RECOVERY_FAILED',
  ERROR: 'ERROR'
});

function isValidRecoveryState(state) {
  return Object.values(RECOVERY_STATES).includes(state);
}

module.exports = {
  RECOVERY_STATES,
  isValidRecoveryState
};
