const UPDATE_NOTIFICATION_STATES = Object.freeze({
  UNKNOWN: 'UNKNOWN',
  WAITING: 'WAITING',
  CONNECTED: 'CONNECTED',
  UP_TO_DATE: 'UP_TO_DATE',
  UPDATE_AVAILABLE: 'UPDATE_AVAILABLE',
  DISPLAYING_NOTIFICATION: 'DISPLAYING_NOTIFICATION',
  DISMISSED: 'DISMISSED',
  ERROR: 'ERROR'
});

module.exports = UPDATE_NOTIFICATION_STATES;
