const SELF_UPDATE_STATES = Object.freeze({
  UNINITIALIZED: 'UNINITIALIZED',
  IDLE: 'IDLE',
  READY: 'READY',
  PREPARING: 'PREPARING',
  PRESERVING_STATE: 'PRESERVING_STATE',
  SHUTTING_DOWN: 'SHUTTING_DOWN',
  INSTALLER_STARTING: 'INSTALLER_STARTING',
  INSTALLER_RUNNING: 'INSTALLER_RUNNING',
  RESTARTING: 'RESTARTING',
  RESTORING: 'RESTORING',
  COMPLETED: 'COMPLETED',
  FAILED: 'FAILED',
  ERROR: 'ERROR'
});

function isValidSelfUpdateState(state) {
  return Object.values(SELF_UPDATE_STATES).includes(state);
}

module.exports = {
  SELF_UPDATE_STATES,
  isValidSelfUpdateState
};
